site_name: EPITA - Documentation
theme: readthedocs
repo_url: https://github.com/epita/epita-doc/
pages:
  - Home: 'index.md'
  - Documentation:
    - PIE: 'pie.md'
    - AFS: 'afs.md'
    - Passwords: 'passwords.md'
    - 'news.md'
  - Procedures:
    - Changing password: 'change_password.md'
  - Contact:  'contact.md'
